### ISSUE TITLE
Can't set config.headers in CDN object

### ISSUE THREAD

**Issue by jsquaredlau** [Nitrolabs/meteor-cdn#11]
Hi Guys,

I'm trying to modify the max age in the headers for the resources, but when running CDN.config() in meteor startup (so using the snippet provided in the readme), it tells me that this is not a function.

Furthermore CDN.get_cdn_url() is apparently also not a function.

Is this a problem anyone else has run into, or am I just doing it incorrectly?

Thanks,
JJ

![screen shot 2017-03-23 at 12 55 01 pm](https://cloud.githubusercontent.com/assets/8555586/24228394/04e1a478-0fc8-11e7-92b0-dc35a61991f3.png)

**Comment by kulttuuri** [comment]
Hey,

Verifying that are you doing this on the serverside? It should not run on the client.

**Comment by jsquaredlau** [comment]
Yes I am attempting to run this on the serverside code. Added a screenshot for reference :)

Does this help?

![screen shot 2017-03-24 at 10 48 45 pm](https://cloud.githubusercontent.com/assets/8555586/24293065/189508bc-10e4-11e7-8032-3406365ed006.png)

**Comment by kulttuuri** [comment]
Ah! I just tried installing the extension with meteor add nitrolabs:cdn and it seems to add old version of the extension (1.2.8) and latest here is version 1.2.10. @maxkferg could you update the extension on atmosphere?

I workaround now to get the latest version working right now is to pull the master branch of this repository and then install the extension locally to your meteor project.

**Comment by maxkferg** [comment]
@kulttuuri and @jsquaredlau. I just published 1.2.10 to atmosphere. Can you confirm that this fixes the problem?

**Comment by jsquaredlau** [comment]
@maxkferg @kulttuuri Yup I can confirm this works now!
Thanks a lot for the speediness guys 😄
