### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by santiagopuentep** [Nitrolabs/meteor-cdn#17]
Hi guys.

I'm using CloudFlare for CDN but I don't know what to put for the CDN url like "http://mydomain.cloudfront.net". Does anyone have any idea where I can find it, because it doesn't seems to be anywhere.

Since CloudFlare makes you change the settings of the DNS nameservers could it be that these settings are not required?

Thanks!

**Comment by kulttuuri** [comment]
For Cloudflare you do not need to set the CDN parameters, resources should be served from CloudFlare CDN automatically. There are some additional tweaks you might to do when using cloudflare, you can read more about that from here: https://forums.meteor.com/t/simple-guide-for-optimising-your-meteor-app-with-cloudflare-cache-ttfb-firewall-etc/41103

You can determine if Cloudflare is working in your Meteor application by opening chrome web developer tools, opening the Network panel, clicking on the css / js / images loaded from your server and seeing if there are some cloudflare related tags, like cf-bgj: minify, cf-cache-status: HIT etc. You can also download CloudFlare Claire chrome extension to check if resources are being served from Cloudflare.

**Comment by santiagopuentep** [comment]
@kulttuuri Thanks a lot for clarifying!

I used those settings and added to html to cache and everything seems to be working fine.
Maybe it would be good to change the Readme to notify newbies like me about Cloudflare.

Closing this.

Thanks!
