### ISSUE TITLE
CDN_URL in javascript

### ISSUE THREAD

**Issue by kulttuuri** [Nitrolabs/meteor-cdn#4]
Would it be possible to use the CDN_URL in javascript code? I've done this kind of code in one of my global files so I can use the CDN_URL variable whenever I want to, but not sure if you can register something like this available through the extension?

```
// Allows using variable CDN_URL anywhere in the javascript code to get the url
// to CDN server ("" if not set)
function get_cdn_url() {
	return __meteor_runtime_config__.CDN_URL || "";
}
CDN_URL = get_cdn_url();
```

Now I can do for ex. something like this in one of my javascript files:
```
sweetAlert.loading = function(title, text) {
	sweetAlert({
	  imageUrl: CDN_URL + "/img/loading.svg",
	  ...
```

**Comment by maxkferg** [comment]
@kulttuuri. Thanks for this suggestion. I'm surprised that we never added this feature when we wrote the package. Without testing, I feel that this could be implemented by adding the following code to [client.js](https://github.com/Nitrolabs/meteor-cdn/blob/master/lib/client.js)

```
// Allows using variable CDN_URL anywhere in the javascript code to get the url
// to CDN server ("" if not set)
CDN.get_cdn_url = function(){
	return __meteor_runtime_config__.CDN_URL || "";
}
```
This solution should work as long as __meteor_runtime_config__.CDN_URL is available immediately (during page load). We are happy to merge in any pull request that implements this.

**Comment by kulttuuri** [comment]
Cool, I'll give a stab on this :)

**Comment by kulttuuri** [comment]
CDN object is only exported in server, I'll need to expose this in the client too. Adding this function also only in client would not make it available in server, need to add this function available for both ends.

Would it make sense to make the CDN object available in new file which would be loaded in both client & server? Or should I just create the CDN object twice in both client & server files and then export it in the package.js from both ends?
