### ISSUE TITLE
Ability to change cache-headers max-age for files in public folder

### ISSUE THREAD

**Issue by kulttuuri** [Nitrolabs/meteor-cdn#6]
Right now all files in public folder do have these kind of cache-control headers: **public, max-age=0**

This means that the files in public folder are always fetched back to CDN, which doesn't really then give any benefit for adding the CDN_URL in front of any static assets. I have done this kind of thing in my server startup script:
```
if (Meteor.settings.public.PRODUCTION) {
	if (Meteor.isServer) {
		WebApp.rawConnectHandlers.use('/', function(req, res, next) {
			if (req._parsedUrl.path.startsWith("/swifticons") ||
				req._parsedUrl.path.startsWith("/gameicons") ||
				req._parsedUrl.path.startsWith("/landing") ||
				req._parsedUrl.path.startsWith("/animal_icons") ||
				req._parsedUrl.path.startsWith("/packages/fortawesome_fontawesome/upstream/fonts") ||
				req._parsedUrl.path.startsWith("/img") ||
				req._parsedUrl.path.startsWith("/largeiconpack") ||
				req._parsedUrl.path.startsWith("/robot") ||
				req._parsedUrl.path.startsWith("/skillicons") ||
				req._parsedUrl.path.startsWith("/tutorial"))
				res.setHeader('cache-control', 'public, max-age=3000');
			next();
		});
	}
}
```

Now after doing this, all files in certain folders on my public folder are actually cached and are being pulled from CDN each time the request comes into it. I have verified this and cloudfront also adds this kind of header to confirm it: x-cache:Hit from cloudfront. I've made the max-age to 3000 seconds so it's quite low as I might change some assets at times. This could be higher.

It would be great to actually set these public folder / file TTLs that you want to serve from CDN yourself using this extension, by somehow passing these settings for the extension. I am not very familiar with how you can pass settings for a Meteor extension, any pointers here? :) Is only way passing parameters just ENV variable? @maxkferg 

One way probably would be setting ENV variable like this: **CDN_PUBLIC_ASSET_MAX_AGES="swifticons=60000|img=3000|largeiconpack/icons.zip=6000"** where things are in this kind of format: **"path=timeToLive|path2=timeToLive2"** and we can split it up with regexp and create similar WebApp.rawConnectHandler.

**Comment by maxkferg** [comment]
@kulttuuri. This is a very relevant and insightful suggestion. I am surprised that the files have the  **public, max-age=0**, but it seems that this header is set on most Meteor production sites (with or without this package). 

I took some time to think whether this feature should be part of the Meteor CDN package. I agree, that the ability to control headers on static resources is a important/relevant function for this package. Therefore, we are happy to merge any pull requests that implement this functionality.
As this feature is not a major concern for us (Nitrolabs) internally, we are not prepared to write/test the entire feature, but we would are happy to provide guidance/code/suggestions to anyone who would like to implement this.

In terms of implementation, the most suitable method is to add a configuration function to the CDN package. The CDN package exposes the `CDN` object on the server and client. Therefore, a configuration function could be added to the server side:

`
CDN.config({
      headers: {
          "*": { "cache-control": public, max-age=},
          "img": {"cache-control": public, "max-age=1000"},
          "swifticons": { "cache-control": "public, max-age=6000"},
          "largeiconpack/icons.zip": {"cache-control": "public, max-age=4000"}
     }
})
`

I feel that this method is slightly cleaner than using environment variables*. Internally, the CDN package would loop through config.headers and add WebApp middleware, just the example code you provided.

*We chose to use an environment variable (CDN_URL) to make the transition from testing/staging/production easy, and the behavior of the package explicit.

**Comment by kulttuuri** [comment]
Yup, public folder has the max-age of 0 because on development and when testing your site (or having lots of changing assets), you don't need things cached. However on production this doesn't make much sense for things that are just static and do not change, you definitely want to cache them on the browser and not load everytime from the server.

That object way seems like a good way to go on on editing the config, I'll try to give a stab on this this weekend and make a PR.

Btw; is the **host** header in whitelist typo in the readme? I've tried using it but always when passing to to cloudfront, my site never loads anymore from CDN. Using **origin** on whitelisting works however, did you mean **origin** instead of **host**? :)
